apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: sonarqube
  name: sonarqube
  namespace: cicd
spec:
  host: sonarqube-cicd.apps.cluster-cra-016e.cra-016e.example.opentlc.com
  to:
    kind: Service
    name: sonarqube
    weight: 100
  wildcardPolicy: None
status:
  ingress: []
