apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: rl-backend
    app.kubernetes.io/component: rl-backend
    app.kubernetes.io/instance: rl-backend
    app.kubernetes.io/part-of: rl-backend-app
  name: rl-backend
  namespace: rl-dev
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    app: rl-backend
    deploymentconfig: rl-backend
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: rl-backend
        deploymentconfig: rl-backend
    spec:
      containers:
      - imagePullPolicy: IfNotPresent
        name: rl-backend
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - rl-backend
      from:
        kind: ImageStreamTag
        name: rl-backend:dev
        namespace: cicd
    type: ImageChange
  - type: ConfigChange
