apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  creationTimestamp: '2019-09-04T16:14:31Z'
  labels:
    app: angular-build
  name: rl-frontend-build
  namespace: cicd
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: 'rl-frontend:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'nginx:1.12'
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers: []
status:
  lastVersion: 0
