apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: backend-build
  name: rl-backend-build
  namespace: cicd
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: 'rl-backend:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'redhat-openjdk18-openshift:1.4'
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers: []
status:
  lastVersion: 0
